* Story Page
** Wintered logo is based on the Wicked stage musical poster.
** Short video is based on video intro to Rudolph the Red-Nosed Reindeer
 #+HTML: <iframe width="560" height="315" src="https://www.youtube.com/embed/g9ByiEGfAXk?rel=0&amp;start=99" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

* North Pole and Beyond
** Stocking

The text field for entering the SHA1 hashes of the great book pages appears to have some placeholder text in it, =686579212121202d436f756e746572204861636b=. This is in hex and can be converted to ascii, =hey!!! -Counter Hack=.

** Exploration

*** Star Wars robots references in http://nppd.northpolechristmastown.com/robots.txt

The robots.txt page for the nppd site has a number of robot references as user-agents.
  * hk-47, a hunter-killer assassin droid
  * threepio, an obvious reference to C3PO. There's a sand-crawler-delay variable set to '421' which could be a reference to the storm trooper, TK-421, who was abushed on the Millenium Falcon, and incidentally is also the only named Storm Trooper in the original trilogy.
  * artoo, an obvious reference to R2D2. There's a sand-craler-delay variable set to '2187' which is likely a reference to the cell that Princess Leia was in on the Death Star.

*** Munchkins
In the Munchin BOLO, the munchkins disappeared after speaking something that sounded like 'puuurzgexgull'. This is most likely a reference to the word 'pyrzqxgl' which was a word described in the book 'The Magic of Oz'. A munchkin, incidentally named 'Bini Aru', like the munchkin in the BOLO, wrote down how to pronounce the word. The word was magical and could be used to transform a being into a different creature. Also, Boq is another munchkin named in the Land of Oz book series.
