* Answer Template
  :PROPERTIES:
  :CUSTOM_ID: answer-template
  :END:

** Question
   :PROPERTIES:
   :CUSTOM_ID: question
   :END:

2) Investigate the Letters to Santa application at
   https://l2s.northpolechristmastown.com. What is the topic of The
   Great Book page available in the web root of the server? What is
   Alabaster Snowball's password?

** Background Information
   :PROPERTIES:
   :CUSTOM_ID: background-information
   :END:

The IP address of =l2s.northpolechristmastown.com= is =35.185.84.51=. Visiting in
reveals a simple web page for sending a very basic letter to Santa. If we look at
the ssl certificate for the host we can see it's actually a certificate for
=dev.northpolechristmastown.com=.

#+BEGIN_SRC sh

#+END_SRC

Hints:

List any useful hints here.

Blog Posts:

- Why You Need the Skills to Tinker with Publicly Released Exploit Code
  https://pen-testing.sans.org/blog/2017/12/05/why-you-need-the-skills-to-tinker-with-publicly-released-exploit-code
  Mentions Apache struts vulnerabilities, specifically CVE-2017-5638 and
  CVE-2017-9805 Code: https://github.com/chrisjd20/cve-2017-9805.py
- A Spot of Tee
  https://pen-testing.sans.org/blog/2017/12/06/a-spot-of-tee Restricted
  bash shell, and bypassing the I/O restriction with tee

** Goal
   :PROPERTIES:
   :CUSTOM_ID: goal
   :END:

What are we trying to accomplish?

** Approach
   :PROPERTIES:
   :CUSTOM_ID: approach
   :END:

Describe the thought process that we tried here. How were we able to use
the hints or the blog posts?

** Solution
   :PROPERTIES:
   :CUSTOM_ID: solution
   :END:

Summarize the reference solution that we found

** Alternatives
   :PROPERTIES:
   :CUSTOM_ID: alternatives
   :END:

Any other, easier solutions?

** Common Pitfalls
   :PROPERTIES:
   :CUSTOM_ID: common-pitfalls
   :END:

Do we know what issue(s) people were running into?

** About the Challenge
   :PROPERTIES:
   :CUSTOM_ID: about-the-challenge
   :END:

How was the challenge setup? Was there a better way to secure this
system?
