* Question
   :PROPERTIES:
   :CUSTOM_ID: q5_question
   :END:

How many infractions are required to be marked as naughty on Santa's
Naughty and Nice List? What are the names of at least six insider
threat moles? Who is throwing the snowballs from the top of the North
Pole Mountain and what is your proof?

/Minty Candycane offers some tips for this challenge in the North Pole and Beyond./

* Background Information
   :PROPERTIES:
   :CUSTOM_ID: q5_background-information
   :END:

We need to answer 3 questions involving infractions, insider moles and who is throwing snowballs. We need 4 things to answer these questions.

  * We need data from the [[http://nppd.northpolechristmastown.com/][North Pole Police Department]]'s [[http://nppd.northpolechristmastown.com/infractions][infractions]] page.
  * We need the naughty and nice list from the SMB server that we accessed from question 3.
  * We need the Munchkin Mole Report BOLO also on the SMB server.
  * We need to complete the "Bumble's Bounce" level on the WebGL game in order to unlock a chat from Sam.

* Goal
   :PROPERTIES:
   :CUSTOM_ID: q5_goal
   :END:

  * We need to identify what factors trigger a 'naughty' flag.
  * We need to identify the six insider threat moles.
  * We need to identify who is throwing snow balls.

* Approach
   :PROPERTIES:
   :CUSTOM_ID: q5_approach
   :END:

Playing around with the infractions page we can see that once you do a search a Download option becomes available to download all the search results in json format. Let's automate this to create a local copy of all the data. We can do this searching for all results before and during a specific date, and all results after that date. We then combine those results into a single file. We can automate this with a script we'll call =nppd.py=.

#+BEGIN_SRC python
#!/usr/bin/env python3
import requests
import json

BASE = "http://nppd.northpolechristmastown.com/"

def search_infractions(query):
    url = BASE + "infractions"

    params = {
        "json": "1",
        "query": query,
    }
    resp = requests.get(url, params=params).json()
    return resp['infractions']


def download_infractions():
    old = search_infractions("date <= 2017-12-10")
    recent = search_infractions("date > 2017-12-10")
    all_infractions = old+recent

    print("Old infractions", len(old))
    print("Recent infractions", len(recent))
    print("Total infractions", len(all_infractions))

    with open("infractions.json", 'w') as f:
        json.dump(all_infractions, f, indent=4)

if __name__ == "__main__":
    download_infractions()
#+END_SRC

Calling =nppd.py= creates a file 'infractions.json'. Now that we have
the NPPD's infractions database we need compare it to the Naughty and
Nice file we found on the SMB server. We can automate this process
scriptomagically. While we're at it we should also script identifying
the 6 insider threat moles as well. For finding the moles it appears
their characteristics are pulling hair and throwing rocks. One caveat
here is that there are two separate infractions for throwing rocks:
"Throwing rocks (non-person target)" and "Throwing rocks (at
people)". We'll include both, since we'd rather have a false positive
than a false negative at this point in our investigation.  We'll try
to identify people on the infractions list that pull hair, and throw
rocks, regardless of their target.

To get the number of infractions needed to get onto the naughty list we take the names on the Naughty and Nice List that have been marked as =Naughty= and count the total number of infractions for those people and we identify the lowest number of infractions per person amongst all of them.

So to automate all this we'll create script we'll call =analyze_infractions.py= to correlate our data.

#+INCLUDE: "../../tools/analyze_infractions.py" src python

After we run our script we get these results:

#+BEGIN_SRC 
Six insider threat moles:
 Isabel Mehta {'Tantrum in a private facility', 'Aggravated pulling of hair', 'Throwing rocks (non-person target)'}
 Nina Fitzgerald {'Giving super atomic wedgies', 'Aggravated pulling of hair', 'Throwing rocks (at people)', 'Possession of unlicensed slingshot', 'Bedtime violation'}
 Kirsty Evans {'Giving super atomic wedgies', 'Aggravated pulling of hair', 'Throwing rocks (at people)', 'Crayon on walls'}
 Sheri Lewis {'Throwing rocks (at people)', 'Aggravated pulling of hair', 'Possession of unlicensed slingshot', 'Naughty words'}
 Beverly Khalil {'Aggravated pulling of hair', 'Throwing rocks (at people)', 'Playing with matches', 'Possession of unlicensed slingshot', 'General sassing'}
 Christy Srivastava {'Tantrum in a private facility', 'Aggravated pulling of hair', 'Tantrum in public', 'Throwing rocks (non-person target)'}

How many infractions are required to be marked as naughty on Santa's Naughty and Nice List: 4
#+END_SRC


Finally, once we play through the Bumbles Bounce level and get all achievements this chat gets unlocked and we have our answer for who is throwing snowballs.

#+BEGIN_QUOTE
Arrrrrrrrgh! Grrrrrrrr! ROOOOOOOAR!

You've done it! You found out who was throwing the giant snowballs! It was the Abominable Snow Monster. We should have known. Thank you for your great work!

But, you know, he doesn't seem quite himself. Look into his eyes. It almost looks like he has been hypnotized. Something's not right with him.

In fact, he seems to be under someone else's control. We've got to find out who is pulling his strings, or else the real villain will remain on the loose and will likely strike again.

It means, buckle your seatbelt, dear player, because the North Pole is going bye-bye
#+END_QUOTE

* Solution
   :PROPERTIES:
   :CUSTOM_ID: q5_solution
   :END:

It appears we need =4= infractions to make the Naughty list.

Our six insider moles appear to be:
  * Isabel Mehta
  * Nina Fitzgerald
  * Kirsty Evans
  * Sheri Lewis
  * Beverly Khalil
  * Christy Srivastava

According to the unlocked chat with Sam, the person throwing snowballs is =the Abominable Snow Monster=, but maybe under someone else's control.

