* Cryokinetic Magic
  :PROPERTIES:
  :END:

** Question
   :PROPERTIES:
   :CUSTOM_ID: question
   :END:

#+BEGIN_EXAMPLE
                         ___
                        / __'.     .-"""-.
                  .-""-| |  '.'.  / .---. \
                 / .--. \ \___\ \/ /____| |
                / /    \ `-.-;-(`_)_____.-'._
               ; ;      `.-" "-:_,(o:==..`-. '.         .-"-,
               | |      /       \ /      `\ `. \       / .-. \
               \ \     |         Y    __...\  \ \     / /   \/
         /\     | |    | .--""--.| .-'      \  '.`---' /
         \ \   / /     |`        \'   _...--.;   '---'`
          \ '-' / jgs  /_..---.._ \ .'\\_     `.
           `--'`      .'    (_)  `'/   (_)     /
                      `._       _.'|         .'
                         ```````    '-...--'`

    My name is Holly Evergreen, and I have a conundrum.
    I broke the candy cane striper, and I'm near throwing a tantrum.
    Assembly lines have stopped since the elves can't get their candy cane fix.
    We hope you can start the striper once again, with your vast bag of tricks.


    Run the CandyCaneStriper executable to complete this challenge.
#+END_EXAMPLE

** How to find the terminal
   :PROPERTIES:
   :CUSTOM_ID: how-to-find-the-terminal
   :END:

From this game: https://2017.holidayhackchallenge.com/game/3e813a9c-cb34-492e-a317-0dd99c8ca2e7
Direct link: https://docker2017.holidayhackchallenge.com/?challenge=82c16868-a96e-4e4c-955e-5b41f7c5809a&uid=USER_ID

** Background Information
   :PROPERTIES:
   :CUSTOM_ID: background-information
   :END:

Do we know anything about this terminal already?

Blog Posts:

Are any of these useful?

- Putting My Zero Cents In: Using the Free Tier on Amazon Web Services
  (EC2)
  https://pen-testing.sans.org/blog/2017/12/10/putting-my-zero-cents-in-using-the-free-tier-on-amazon-web-services-ec2
  Spinning up an EC2 instance, but also a lot of emphasis on how to use
  SSH keys.
- Your Pokemon Guide for Essential SQL Pen Test Commands
  https://pen-testing.sans.org/blog/2017/12/09/your-pokemon-guide-for-essential-sql-pen-test-commands
  SQL basics (SELECT, WHERE, wildcards, ORDER BY, GROUP BY, COUNT)
- Exploiting XXE Vulnerabilities in IIS/.NET
  https://pen-testing.sans.org/blog/2017/12/08/entity-inception-exploiting-iis-net-with-xxe-vulnerabilities
  Including remote content in XML
- Why You Need the Skills to Tinker with Publicly Released Exploit Code
  https://pen-testing.sans.org/blog/2017/12/05/why-you-need-the-skills-to-tinker-with-publicly-released-exploit-code
  Mentions Apache struts vulnerabilities, specifically CVE-2017-5638 and
  CVE-2017-9805 Code: https://github.com/chrisjd20/cve-2017-9805.py
- Go To The Head Of The Class: LD\_PRELOAD For The Win
  https://pen-testing.sans.org/blog/2017/12/06/go-to-the-head-of-the-class-ld-preload-for-the-win
- A Spot of Tee
  https://pen-testing.sans.org/blog/2017/12/06/a-spot-of-tee Restricted
  bash shell, and bypassing the I/O restriction with tee
- Understanding and Exploiting Web-based LDAP
  https://pen-testing.sans.org/blog/2017/11/27/understanding-and-exploiting-web-based-ldap
  LDAP syntax, LDAP injection
- Massively Scaling your Scanning
  https://pen-testing.sans.org/blog/2017/10/25/massively-scaling-your-scanning
  masscan

** Goal
   :PROPERTIES:
   :CUSTOM_ID: goal
   :END:

What are we trying to accomplish?

** Hints
   :PROPERTIES:
   :CUSTOM_ID: hints
   :END:
   
[[https://twitter.com/GreenesterElf][Holly Evergreen on Twitter has some hints]]
  * [[https://twitter.com/GreenesterElf/status/938542480487677952][Alright, who chmod -x'd and then removed chmod from my system? Not funny! I really need to run a program on this server, for serious. Was it you, @PepperyGoodness ? Weren't you mucking about with ARM64 recently?]]
  * [[https://twitter.com/GreenesterElf/status/938552050253643777][I still can't figure out Pepper Minstix's issue. It looks like the binary is compiled for another architecture. I think qemu can help, but I don't want to run the entire OS :\ https://doc.opensuse.org/documentation/… helps, but I just want one binary, not the whole system!] [[https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha.qemu.running.html]]

** Approach
   :PROPERTIES:
   :CUSTOM_ID: approach
   :END:

Describe the thought process that we tried here. How were we able to use
the hints or the blog posts?

** Solution
   :PROPERTIES:
   :CUSTOM_ID: solution
   :END:

Summarize the reference solution that we found.

AsciiCinema video of the solution?

** Alternatives
   :PROPERTIES:
   :CUSTOM_ID: alternatives
   :END:

Any other, easier solutions?

** Common Pitfalls
   :PROPERTIES:
   :CUSTOM_ID: common-pitfalls
   :END:

Do we know what issue(s) people were running into?

** About the Challenge
   :PROPERTIES:
   :CUSTOM_ID: about-the-challenge
   :END:

How was the challenge setup? Was there a better way to secure this
system?

** Loot
   :PROPERTIES:
   :CUSTOM_ID: loot
   :END:

Anything interesting hidden on the system?
